### ISSUE TITLE
memberOf support

### ISSUE THREAD

**Issue by shreddedbacon** [making/openldap-boshrelease#2]
Is it possible to get support for memberOf in this release?

**Comment by making** [comment]
Can you send a PR?

**Comment by shreddedbacon** [comment]
I don't know how to enable memberOf, my experience with openldap is very new.

**Comment by making** [comment]
What does "support for memberOf" mean?
What is your problem?

**Comment by shreddedbacon** [comment]
Sorry, trying to be able to do a filter where I can return the members of a group using the `memberOf` query.
https://confluence.atlassian.com/kb/how-to-write-ldap-search-filters-792496933.html

This would be helpful in being able to easily select members from a group to use in similar ways to AD

**Comment by shreddedbacon** [comment]
I tried to follow this guide: https://adimian.com/blog/2014/10/how-to-enable-memberof-using-openldap/ but it looks like this release is missing the modules

**Comment by making** [comment]
you can use `ldapadd` in [add-dn](https://github.com/making/openldap-boshrelease/blob/master/jobs/add-dn/spec) errand
you can use `ldapmodify` in [modify-dn](https://github.com/making/openldap-boshrelease/blob/master/jobs/modify-dn/templates/run.sh.erb) as well

**Comment by making** [comment]
Hi @shreddedbacon 
`memberOf` has been supported in [`0.10.0`](https://github.com/making/openldap-boshrelease/releases/tag/0.10.0).

Please take a look.

**Comment by shreddedbacon** [comment]
Thank you for looking into this! I will try it out
